pub mod armstrong_number;
pub mod calculator;
pub mod factorial_number;
pub mod fibonacci;
pub mod largest_number;
pub mod leap_year;
pub mod multiplication_table;
pub mod odd_number;
pub mod palindrome_number;
pub mod prime_number;
pub mod reverse_integer;
pub mod reverse_number;
pub mod swap_two_numbers;
// pub mod lcm;
